# Aritmetic Operations:

# (1.) 1-D Array:

Adding elements of array with an another elemnt:

In [1]:
import numpy as np

var = np.array([1,2,3,4])

varadd = var + 3
print(varadd)

[4 5 6 7]


In [8]:
var = np.array([1,2,3,4])

varadd = np.add(var,3)
print(varadd)

[4 5 6 7]


Adding two different array:

In [2]:
var1 = np.array([1,2,3,4])
var2 = np.array([1,2,3,4])
varadd = var1 + var2
print(varadd)

[2 4 6 8]


In [7]:
var1 = np.array([1,2,3,4])
var2 = np.array([1,2,3,4])
varadd = np.add(var1,var2)
print(varadd)

[2 4 6 8]


Subtraction:

In [3]:
var = np.array([1,2,3,4])

varadd = var - 3
print(varadd)

[-2 -1  0  1]


Multiplication

In [4]:
var = np.array([1,2,3,4])

varadd = var * 3
print(varadd)

[ 3  6  9 12]


Divide:

In [5]:
var = np.array([1,2,3,4])

varadd = var/3
print(varadd)

[0.33333333 0.66666667 1.         1.33333333]


Modulus:

In [6]:
var = np.array([1,2,3,4])

varadd = var%3
print(varadd)

[1 2 0 1]


Reciprocal:

In [13]:
var = np.array([1,2,3,4])

varadd = np.reciprocal(var)
print(varadd)

[1 0 0 0]


# (2) 2-D Array:

Add:

In [ ]:
var21 = np.array([[1,2,3,4],[1,2,3,4]])
var22 = np.array([[1,2,3,4],[1,2,3,4]])

print(var21)
print()
print(var22)
print()

varadd2 = var21 + var22

print(varadd2)

[[1 2 3 4]
 [1 2 3 4]]

[[1 2 3 4]
 [1 2 3 4]]

[[2 4 6 8]
 [2 4 6 8]]


Multiply:

In [12]:
var21 = np.array([[1,2,3,4],[1,2,3,4]])
var22 = np.array([[1,2,3,4],[1,2,3,4]])

print(var21)
print()
print(var22)
print()

varadd2 = var21 * var22

print(varadd2)

[[1 2 3 4]
 [1 2 3 4]]

[[1 2 3 4]
 [1 2 3 4]]

[[ 1  4  9 16]
 [ 1  4  9 16]]
