# 1. Shuffle():

1D Array:

In [3]:
import numpy as np

var = np.array([1,2,3,4,5])

np.random.shuffle(var)

print(var)

[2 5 4 1 3]


2D Array:

In [6]:
var = np.array([[1,2],[3,4],[5,6]])

np.random.shuffle(var)

print(var)

[[5 6]
 [1 2]
 [3 4]]


# 2. Unique():

In [10]:
var1 = np.array([1,2,3,4,2,5,2,4,1,6,7])

print(np.unique(var1))
print(np.unique(var1,return_index=True))
print(np.unique(var1,return_index=True,return_counts=True))

[1 2 3 4 5 6 7]
(array([1, 2, 3, 4, 5, 6, 7]), array([ 0,  1,  2,  3,  5,  9, 10]))
(array([1, 2, 3, 4, 5, 6, 7]), array([ 0,  1,  2,  3,  5,  9, 10]), array([2, 3, 1, 2, 1, 1, 1]))


# 3. Resize():

In [ ]:
var2 = np.array([1,2,3,4,5,6])

y = np.resize(var2,(2,3))   # np.resize(array,(no. of row, no. of col))

print(y)

[[1 2 3]
 [4 5 6]]


# 4. Flatten():

In [20]:
var2 = np.array([1,2,3,4,5,6])

y = np.resize(var2,(2,3))
print(y)
print()
print(y.flatten())  # By Default order is: 'C'
print()
print("Flatten: ",y.flatten(order="F"))   
print()
print("Ravel: ",y.ravel())
print()
print("Ravel: ",np.ravel(y,order="F"))

[[1 2 3]
 [4 5 6]]

[1 2 3 4 5 6]

Flatten:  [1 4 2 5 3 6]

Ravel:  [1 2 3 4 5 6]

Ravel:  [1 4 2 5 3 6]
