# 1. Search():

In [2]:
import numpy as np

var = np.array([4,2,3,4,2,5,2,5,6,7])

x = np.where(var == 2)
print(x)
print()

x = np.where((var%2) == 0)
print(x)
print()

(array([1, 4, 6]),)

(array([0, 1, 3, 4, 6, 8]),)



# 2. Search-Sorted():

In [8]:
var1 = np.array([1,2,3,4,6,7,8,9,10])

x1 = np.searchsorted(var1,5)  # By Default it move left to right
print(x1)
print()

x2 = np.searchsorted(var1,5,side="right")  #  Now it move right ot left
print(x2)
print()

var2 = np.array([1,2,3,8,9,10])
x1 = np.searchsorted(var2,[4,5,6,7],side='right')  # By Default it move left to right
print(x1)
print()

4

4

[3 3 3 3]



# 3. Sort():

In [9]:
var_1 = np.array([4,2,3,1,12,5,22,52,6,7])

print(np.sort(var_1))

[ 1  2  3  4  5  6  7 12 22 52]


In [11]:
var_1 = np.array(["b","s","r","a","g","t","e","A","T"])

print(np.sort(var_1))

['A' 'T' 'a' 'b' 'e' 'g' 'r' 's' 't']


In [12]:
var_1 = np.array([[4,2,3],[1,12,5],[22,52,6]])

print(np.sort(var_1))

[[ 2  3  4]
 [ 1  5 12]
 [ 6 22 52]]


# 4. Filter Array:

In [14]:
var_3 = np.array(["a","s","d","f"])

f = [True,False,False,True]

new_a = var_3[f]
print(new_a)
print(type(new_a))

['a' 'f']
<class 'numpy.ndarray'>
