In [1]:
import numpy as np

var1 = np.array([1,2,3,4])
var2 = np.array([1,2,3])
print(var1 + var2)

ValueError: operands could not be broadcast together with shapes (4,) (3,) 

This is broadcast error

In [7]:
var1 = np.array([1,2,3])
print(var1)
print(var1.shape)
print()

var2 = np.array([[1],[2],[3]])
print(var2)
print(var2.shape)
print()

print(var1 + var2)


[1 2 3]
(3,)

[[1]
 [2]
 [3]]
(3, 1)

[[2 3 4]
 [3 4 5]
 [4 5 6]]


In [10]:
x = np.array([[1],[2]])
print(x.shape)

y = np.array([[1,2,3],[1,2,3]])
print(y.shape)

print(x+y)

(2, 1)
(2, 3)
[[2 3 4]
 [3 4 5]]
