# Zero Array:

In [4]:
import numpy as np
ar_zero = np.zeros(4)
ar_zero1 = np.zeros((3,4))    # Array of size (3,4) with 0 elements created
print(ar_zero)
print()
print(ar_zero1)

[0. 0. 0. 0.]

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


# One's Array:

In [5]:
ar_one = np.ones(4)
print(ar_one)

[1. 1. 1. 1.]


# Empty Array:

In [ ]:
ar_em = np.empty(4)
print(ar_em)         # But here it show array of 1 bcz in empty array the elements of previous array stored

[1. 1. 1. 1.]


# Range Array:

In [ ]:
ar_rn = np.arange(4)    # we can also give value as: np.arange(0,4)
print(ar_rn)

[0 1 2 3]


# Digonal Array:

In [9]:
ar_dia = np.eye(3)
print(ar_dia)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [10]:
ar_dia = np.eye(3,5)
print(ar_dia)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]]


# Linespace Array:

In [13]:
ar_lin = np.linspace(0,20,num=5)   # np.linspace(from,to,no.of elements)
print(ar_lin)

[ 0.  5. 10. 15. 20.]
