# Random Array:

# 1. Rand()

In [2]:
import numpy as np

var = np.random.rand(5)
print(var)

[0.31144253 0.52261085 0.76173653 0.70709088 0.75354733]


2-D Array:

In [ ]:
var1 = np.random.rand(2,5)   # Array of size(2,5)
print(var1)

[[0.70975609 0.05145273 0.91919114 0.80427332 0.53560079]
 [0.72324095 0.02301795 0.93768911 0.66686811 0.30670217]]


# 2. Randn():

In [4]:
var2 = np.random.randn(5)
print(var2)

[ 0.41554886 -0.15890271  1.00154545 -1.7895491   0.4212139 ]


# 3. Ranf():

In [5]:
var3 = np.random.ranf(4)
print(var3)

[0.69615083 0.56560734 0.28066129 0.72083633]


# 4. Randint():

In [10]:
var4 = np.random.randint(5,20,5)     # np.random.randint(from,to,no. of elements want to generate)
print(var4)

[15 11  7 11  5]
