# Array:

In [8]:
import numpy as np
x = [1,2,3,4]
y = np.array(x)
print(y)  # it just print array elements
y         # it print both elements along with its data type  (only posiible in jupyter notebook)
print(y.ndim)

[1 2 3 4]
1


User Defined Array:

In [7]:
l = []
for i in range(1,5):
    int_1 = int(input("Enter: "))    # We are using int() bcz in input() we get elements in string type
    l.append(int_1)

print(np.array(l))

[11 13 12 15]


2-D Array:

In [9]:
ar2 = np.array([[1,2,3,4],[1,2,3,4]])
print(ar2)
print(ar2.ndim)

[[1 2 3 4]
 [1 2 3 4]]
2


3-D Array:

In [10]:
ar3 = np.array([[[1,2,3,4,5],[1,2,3,4,5],[1,2,3,4,5]]])
print(ar3)
print(ar3.ndim)

[[[1 2 3 4 5]
  [1 2 3 4 5]
  [1 2 3 4 5]]]
3


N-D Array:

In [19]:
arn = np.array([1,2,3,4,5], ndmin = 10)
print(arn)
print(arn.ndim)

[[[[[[[[[[1 2 3 4 5]]]]]]]]]]
10
