# Data Types:

In [ ]:
import numpy as np

var = np.array([1,2,3,4,12,13,14,15])
print("Data Type: ",var.dtype)

Data Type:  int64


In [4]:
var1 = np.array([1,0,0.2,0.6,5])
print("Data Type: ",var1.dtype)

Data Type:  float64


String:

In [5]:
var = np.array(['a', 's', 'd', 'e'])
print("Data Type: ",var.dtype)

Data Type:  <U1


In [8]:
var = np.array(['a','e',1,2,3,4,5])
print("Data Type: ",var.dtype)

Data Type:  <U21


# To change the datatype from one to another:

In [9]:
x = np.array([1,2,3,4])
print("Data Type: ", x.dtype)

Data Type:  int64


Now changing this datatype:

In [13]:
x = np.array([1,2,3,4],dtype = np.int8)
print("Data Type: ", x.dtype)
print(x)

Data Type:  int8
[1 2 3 4]


Now to convert it into float:

In [14]:
x1 = np.array([1,2,3,4],dtype = "f")
print("Data Type: ", x1.dtype)
print(x1)

Data Type:  float32
[1. 2. 3. 4.]


To use data type as a function:

In [19]:
x2 = np.array([1,2,3,4])

new = np.float32(x2)

new_one = np.int_(new)

print(x2)
print("Data Type: ", x2.dtype)
print(new)
print("Data Type: ", new.dtype)
print(new_one)
print("Data Type: ", new_one.dtype)

[1 2 3 4]
Data Type:  int64
[1. 2. 3. 4.]
Data Type:  float32
[1 2 3 4]
Data Type:  int64


In above:-  first list -> int (bcz of np.array())  ->  float (bcz np.float32())   -> int (bcz of np.int_())

# To directly convert it without using functions:

In [25]:
x3 = np.array([1,2,3,4])

new_1 = x3.astype(float)

print(x3)
print("Data Type: ", x3.dtype)
print(new_1)
print("Data Type: ", new_1.dtype)

[1 2 3 4]
Data Type:  int64
[1. 2. 3. 4.]
Data Type:  float64
