# Indexing:

1D Array:

In [3]:
import numpy as np

var = np.array([1,2,3,4,5])
#  Indexing:    0 1 2 3 4 
#  Indexing:   -5 -4 -3 -2 -1   

print(var[2])
print(var[-2])

3
4


2D Array:

In [5]:
var1 = np.array([[9,8,7],[4,5,6]])

print(var1)
print(var1.ndim)
print()

print(var1[0,1])

[[9 8 7]
 [4 5 6]]
2

8


3D Array:

In [8]:
var3 = np.array([[[1,2],[6,7]]])

print(var3)
print(var3.ndim)
print()

print(var3[0,1,1])

[[[1 2]
  [6 7]]]
3

7
