# Iteration:

1D Array:

In [1]:
import numpy as np

var = np.array([9,8,7,6,5,4,3,2])
print(var)
print()

for i in var:
    print(i)

[9 8 7 6 5 4 3 2]

9
8
7
6
5
4
3
2


2D Array:

In [4]:
var1 = np.array([[1,2,3,4,5],[9,8,7,6,5]])
print(var1)
print()

for j in var1:
    print(j)

print()

for k in var1:
    for l in k:
        print(l)

[[1 2 3 4 5]
 [9 8 7 6 5]]

[1 2 3 4 5]
[9 8 7 6 5]

1
2
3
4
5
9
8
7
6
5


3D Array:

In [8]:
var3 = np.array([[[1,2,3],[4,5,6],[7,8,9]]])

print(var3)
print(var3.ndim)
print()

for a in var3:
    for b in a:
        for c in b:
            print(c)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]
3

1
2
3
4
5
6
7
8
9


Iteration using functions: using nditer()

In [10]:
var4 = np.array([[[1,2,3],[4,5,6],[7,8,9]]])

print(var4)
print(var4.ndim)
print()

for i in np.nditer(var4):
    print(i)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]
3

1
2
3
4
5
6
7
8
9


To change the datatype of Iterated elements:   use 'Buffer'

In [ ]:
var5 = np.array([[[1,2,3],[4,5,6],[7,8,9]]])

print(var5)
print(var5.ndim)
print()

for i in np.nditer(var5,flags=['buffered'],op_dtypes=['S']):    # 'S' is for to change int into string
    print(i)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]
3

np.bytes_(b'1')
np.bytes_(b'2')
np.bytes_(b'3')
np.bytes_(b'4')
np.bytes_(b'5')
np.bytes_(b'6')
np.bytes_(b'7')
np.bytes_(b'8')
np.bytes_(b'9')


Want to get the address of iterated elements: ndenumerate()

In [13]:
var6 = np.array([[[1,2,3],[4,5,6],[7,8,9]]])

print(var6)
print(var6.ndim)
print()

for i,d in np.ndenumerate(var6):    # 'S' is for to change int into string
    print(i,d)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]
3

(0, 0, 0) 1
(0, 0, 1) 2
(0, 0, 2) 3
(0, 1, 0) 4
(0, 1, 1) 5
(0, 1, 2) 6
(0, 2, 0) 7
(0, 2, 1) 8
(0, 2, 2) 9
