# Join Array:

Joining 1D Array: Using Concatenate()

In [10]:
import numpy as np

var = np.array([1,2,3,4])
var1 = np.array([9,8,7,6])

ar = np.concatenate((var,var1))
print(ar)

[1 2 3 4 9 8 7 6]


In [9]:
var = np.array([1,2,3,4,5])
var1 = np.array([9,8,7,6])

ar = np.concatenate((var,var1))
print(ar)

[1 2 3 4 5 9 8 7 6]


Joining 2D Array: Using Concatenate()

In [15]:
var2 = np.array([[1,2],[3,4]])
var3 = np.array([[9,8],[7,6]])
print(var2)
print()
print(var3)
print()

arr = np.concatenate((var2,var3),axis=0)
print(arr)
print()

arrr = np.concatenate((var2,var3),axis=1)
print(arrr)


[[1 2]
 [3 4]]

[[9 8]
 [7 6]]

[[1 2]
 [3 4]
 [9 8]
 [7 6]]

[[1 2 9 8]
 [3 4 7 6]]


Joining 1D Array: Using Stack()

In [ ]:
var4 = np.array([1,2,3,4])
var5 = np.array([9,8,7,6])

ar_new = np.stack((var4,var5))
print(ar_new)
print()

ar_new = np.stack((var4,var5),axis=0)
print(ar_new)
print()

ar_new = np.stack((var4,var5),axis=1)
print(ar_new)
print()

ar_new = np.hstack((var4,var5))   # Work along Row
print(ar_new)
print()

ar_new = np.vstack((var4,var5))   # Work along Column
print(ar_new)
print()

ar_new = np.dstack((var4,var5))   # Work along Height
print(ar_new)
print()

[[1 2 3 4]
 [9 8 7 6]]

[[1 2 3 4]
 [9 8 7 6]]

[[1 9]
 [2 8]
 [3 7]
 [4 6]]

[1 2 3 4 9 8 7 6]

[[1 2 3 4]
 [9 8 7 6]]

[[[1 9]
  [2 8]
  [3 7]
  [4 6]]]

