# Shape:

In [4]:
import numpy as np

var = np.array([[1,2,3,4],[1,2,3,4]])

print(var)
print()
print(var.shape)

[[1 2 3 4]
 [1 2 3 4]]

(2, 4)


In [9]:
var1 = np.array([1,2,3,4],ndmin=4)
print(var1)
print(var1.ndim)
print()
print(var1.shape)

[[[[1 2 3 4]]]]
4

(1, 1, 1, 4)


# Reshape:

To convert from 1D array to 2D array:

In [14]:
var2 = np.array([1,2,3,4,5,6])

print(var2)
print(var2.ndim)
print()

x = var2.reshape(2,3)  # reshape(no. of rows, no. of columns)

print(x)
print(x.ndim)

[1 2 3 4 5 6]
1

[[1 2 3]
 [4 5 6]]
2


To convert from 1D array to 3D array:

In [15]:
var3 = np.array([1,2,3,4,5,6,7,8,9,10,11,12])

print(var3)
print(var3.ndim)
print()

x = var3.reshape(2,3,2)  # reshape(no. of rows, no. of columns)

print(x)
print(x.ndim)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
1

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]
3


To convert from 3D array to 1D array:

In [17]:
var3 = np.array([1,2,3,4,5,6,7,8,9,10,11,12])

print(var3)
print(var3.ndim)
print()

x = var3.reshape(2,3,2)  # reshape(no. of rows, no. of columns)

print(x)
print(x.ndim)
print()

one = x.reshape(-1)
print(one)
print(one.ndim)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
1

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]
3

[ 1  2  3  4  5  6  7  8  9 10 11 12]
1
