# Slicing:

1D Array:

In [19]:
import numpy as np

var = np.array([9,8,7,6,5,4,3,2])
# Index:        0,1,2,3,4,5,6

print(var)
print()

print("2 to 5: ",var[1:6])
print("2 to 5: ",var[1:6:1])
print(var[1:6:2])
print(var[1:])
print(var[:5])
print(var[::2])
print(var[::-1])
print(var[::])


[9 8 7 6 5 4 3 2]

2 to 5:  [8 7 6 5 4]
2 to 5:  [8 7 6 5 4]
[8 6 4]
[8 7 6 5 4 3 2]
[9 8 7 6 5]
[9 7 5 3]
[2 3 4 5 6 7 8 9]
[9 8 7 6 5 4 3 2]


2D Array:

In [23]:
var1 = np.array([[1,2,3,4,5],[9,8,7,6,5],[11,12,13,14,15]])

print(var1)
print()
print(var1[1,1:])
print(var1[2,1:])

[[ 1  2  3  4  5]
 [ 9  8  7  6  5]
 [11 12 13 14 15]]

[8 7 6 5]
[12 13 14 15]
