# Spilt Array:

Splitting 1D Array:

In [6]:
import numpy as np

var = np.array([1,2,3,4,5,6])
print(var)
print()

ar = np.array_split(var,2)
print(ar)
print(type(ar))
print()

arr = np.array_split(var,3)
print(arr)
print(type(arr))
print(arr[0],type(arr[0]))

[1 2 3 4 5 6]

[array([1, 2, 3]), array([4, 5, 6])]
<class 'list'>

[array([1, 2]), array([3, 4]), array([5, 6])]
<class 'list'>
[1 2] <class 'numpy.ndarray'>


Splitting 2D Array:

In [9]:
var1 = np.array([[1,2],[3,4],[5,6]])
print(var1)
print()

ar = np.array_split(var1,2)
print(ar)
print(type(ar))
print()

arr = np.array_split(var1,3)
print(arr)
print(type(arr))
print(arr[0],type(arr[0]))
print()

ar2 = np.array_split(var1,3,axis=1)
print(ar2)

[[1 2]
 [3 4]
 [5 6]]

[array([[1, 2],
       [3, 4]]), array([[5, 6]])]
<class 'list'>

[array([[1, 2]]), array([[3, 4]]), array([[5, 6]])]
<class 'list'>
[[1 2]] <class 'numpy.ndarray'>

[array([[1],
       [3],
       [5]]), array([[2],
       [4],
       [6]]), array([], shape=(3, 0), dtype=int64)]
